### ISSUE TITLE
[🎙️] Obsidian

### ISSUE THREAD

**Issue by jtprogru** [jtprogru/voiceops#15]
## TL;DR

В очередной раз уперевшись в неудобство Notion, я понял, что надо вернуться обратно на Obsidian – он более гибкий для работы с заметками.

## Questions
Вопросы, которые стоит подсветить в этой теме:

- [x] Неудобство Notion?
- [x] Топ полезных плагинов?
- [x] Дашборды?
- [x] Организация контента?

Стоит дополнительно позвать:

- [x] @ikurochkin 
- [x] @tomakado

**Comment by ikurochkin** [comment]
1. Я бы предложил начать с обсуждения неудобств Notion
2. Плагины, дашборды, контент - ок
3. Что значит "сделать красиво"?
4. В последнем вопросе можно перейти к теме Obsidian at Scale, когда заметок больше 1к

**Comment by etoosamoe** [comment]
> неудобств Notion

Я бы даже поучаствовал! 😁

**Comment by jtprogru** [comment]
@ikurochkin
1. Согласен, потому что прям спотыкался об это целый месяц;
2. Ok;
3. Годные темы оформления, правильно и удобно расставленные плагины;
4. Согласен, у меня как раз чуть больше 1.2k (надо еще примерно 1-2 сотни перенести из Notion);

**Comment by ikurochkin** [comment]
3. Я использую тему Minimal:) Остальные особо не смотрел. Возможно стоит затронуть тему Properties, они скоро их зарелизят https://twitter.com/obsdmd/status/1684275039703814145, а также Dataview, DB Folder, Activity History, Graph Analysis, Vault stats плагины.
4. Можем еще обсудить Obsidian для задач и плагин Tasks.
